# Generated by Django 2.0 on 2018-09-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='httpdinstance',
            fields=[
                ('apache_id', models.AutoField(primary_key=True, serialize=False)),
                ('apache_ciname', models.CharField(max_length=250)),
                ('apache_appname', models.CharField(max_length=250)),
                ('apache_server', models.CharField(max_length=250)),
                ('apache_vipurl', models.CharField(max_length=250)),
                ('apache_instance_group', models.CharField(max_length=250)),
                ('apache_user', models.CharField(max_length=250)),
                ('apache_httpd_version', models.CharField(max_length=250)),
                ('apache_httpdswitch', models.CharField(blank=True, max_length=250)),
                ('apache_initscript', models.CharField(max_length=250)),
                ('apache_apachescript', models.CharField(max_length=250)),
                ('apache_listen_hostport', models.CharField(max_length=250)),
                ('apache_environment', models.CharField(default='DEV', max_length=250)),
                ('apache_AppDL', models.CharField(blank=True, default='NA', max_length=250)),
                ('apache_Appowner', models.CharField(blank=True, default='NA', max_length=250)),
                ('apache_comments', models.TextField(blank=True)),
                ('apache_datacenter', models.CharField(max_length=250)),
                ('apache_OS', models.CharField(max_length=250)),
                ('apache_OSver', models.CharField(blank=True, default='NA', max_length=250)),
                ('apache_giturl', models.CharField(blank=True, default='NA', max_length=250)),
                ('apache_active', models.BooleanField(default=True)),
            ],
        ),
    ]
